<?php

return [
    'queue_connection' => env('ML_QUEUE_CONNECTION', 'machine_learning'),
    'runner_driver' => env('ML_RUNNER_DRIVER', 'docker'),
    'local_python_binary' => env('ML_LOCAL_PYTHON', 'python'),
    'queue_name' => env('ML_QUEUE_NAME', 'machine-learning'),
    'runner_image' => env('ML_RUNNER_IMAGE', env('PYTHON_SANDBOX_DOCKER_IMAGE', 'datasensei-python-runner:latest')),
    'docker_binary' => env('ML_DOCKER_BINARY', 'docker'),
    'training_timeout_seconds' => (int) env('ML_TRAINING_TIMEOUT', 600),
    'prediction_timeout_seconds' => (int) env('ML_PREDICTION_TIMEOUT', 30),
    'memory' => env('ML_RUNNER_MEMORY', '768m'),
    'memory_swap' => env('ML_RUNNER_MEMORY_SWAP', '768m'),
    'cpus' => env('ML_RUNNER_CPUS', '1.0'),
    'pids_limit' => (int) env('ML_RUNNER_PIDS_LIMIT', 96),
    'max_upload_kilobytes' => (int) env('ML_MAX_UPLOAD_KB', 10240),
    'max_rows' => (int) env('ML_MAX_ROWS', 50000),
    'max_columns' => (int) env('ML_MAX_COLUMNS', 200),
    'preview_rows' => (int) env('ML_PREVIEW_ROWS', 20),
    'max_versions_per_model' => (int) env('ML_MAX_VERSIONS', 0), // 0 means unlimited.
    'max_prediction_history' => (int) env('ML_MAX_PREDICTION_HISTORY', 100),
    'temporary_file_retention_hours' => (int) env('ML_TEMP_RETENTION_HOURS', 24),
    'allowed_test_sizes' => [0.10, 0.20, 0.25, 0.30],
    'allowed_random_states' => [7, 21, 42, 100, 2026],
    'cross_validation_folds' => [0, 3, 5, 10],
    'system_manifest_path' => 'ml/system/manifest.json',
    'system_manifest' => storage_path('app/ml/system/manifest.json'),

    'algorithms' => [
        'logistic_regression' => [
            'problem_type' => 'classification',
            'label' => 'Logistic Regression',
            'description' => 'An interpretable linear classifier that estimates class probabilities.',
            'strengths' => ['Fast to train', 'Easy to explain', 'Strong benchmark for linearly separable data'],
            'weaknesses' => ['May underfit nonlinear relationships', 'Sensitive to unscaled numeric features'],
            'when_not_to_use' => ['Strongly nonlinear data without engineered features', 'Very high-cardinality unstructured text'],
            'expected_training_time' => 'Usually a few seconds for classroom-sized datasets.',
            'supports_probability' => true,
            'supports_feature_importance' => true,
            'defaults' => ['c' => 1.0, 'max_iter' => 1000],
            'parameters' => [
                'c' => ['type' => 'float', 'label' => 'Regularization strength (C)', 'min' => 0.01, 'max' => 100.0, 'step' => 0.01, 'default' => 1.0],
                'max_iter' => ['type' => 'integer', 'label' => 'Maximum iterations', 'min' => 100, 'max' => 3000, 'step' => 100, 'default' => 1000],
            ],
        ],
        'decision_tree' => [
            'problem_type' => 'classification',
            'label' => 'Decision Tree',
            'description' => 'Learns readable decision rules and nonlinear splits.',
            'strengths' => ['Easy to visualize', 'Handles nonlinear patterns', 'Little scaling dependence'],
            'weaknesses' => ['Can overfit quickly', 'Small data changes may alter the tree'],
            'when_not_to_use' => ['Very small noisy datasets without depth limits'],
            'expected_training_time' => 'Usually under a few seconds.',
            'supports_probability' => true,
            'supports_feature_importance' => true,
            'defaults' => ['max_depth' => 6, 'min_samples_split' => 2],
            'parameters' => [
                'max_depth' => ['type' => 'integer', 'label' => 'Maximum depth', 'min' => 2, 'max' => 30, 'step' => 1, 'default' => 6],
                'min_samples_split' => ['type' => 'integer', 'label' => 'Minimum samples to split', 'min' => 2, 'max' => 50, 'step' => 1, 'default' => 2],
            ],
        ],
        'random_forest' => [
            'problem_type' => 'classification',
            'label' => 'Random Forest',
            'description' => 'Combines many decision trees to improve stability and nonlinear performance.',
            'strengths' => ['Strong general-purpose performance', 'Handles nonlinear interactions', 'Provides feature importance'],
            'weaknesses' => ['Less interpretable than one tree', 'Larger models and slower predictions'],
            'when_not_to_use' => ['Strictly linear problems where interpretability is the priority'],
            'expected_training_time' => 'A few seconds to under a minute, depending on rows and trees.',
            'supports_probability' => true,
            'supports_feature_importance' => true,
            'defaults' => ['n_estimators' => 150, 'max_depth' => 10, 'min_samples_split' => 2],
            'parameters' => [
                'n_estimators' => ['type' => 'integer', 'label' => 'Number of trees', 'min' => 25, 'max' => 500, 'step' => 25, 'default' => 150],
                'max_depth' => ['type' => 'integer', 'label' => 'Maximum depth', 'min' => 2, 'max' => 40, 'step' => 1, 'default' => 10],
                'min_samples_split' => ['type' => 'integer', 'label' => 'Minimum samples to split', 'min' => 2, 'max' => 50, 'step' => 1, 'default' => 2],
            ],
        ],
        'knn' => [
            'problem_type' => 'classification',
            'label' => 'K-Nearest Neighbors',
            'description' => 'Classifies a record using the labels of its closest training neighbors.',
            'strengths' => ['Simple concept', 'No complex training stage', 'Useful for local patterns'],
            'weaknesses' => ['Prediction slows as data grows', 'Very sensitive to feature scale and irrelevant features'],
            'when_not_to_use' => ['Large datasets', 'High-dimensional data without feature selection'],
            'expected_training_time' => 'Training is immediate; predictions may become slower as rows increase.',
            'supports_probability' => true,
            'supports_feature_importance' => false,
            'defaults' => ['n_neighbors' => 5, 'weights' => 'uniform'],
            'parameters' => [
                'n_neighbors' => ['type' => 'integer', 'label' => 'Neighbors', 'min' => 1, 'max' => 50, 'step' => 1, 'default' => 5],
                'weights' => ['type' => 'select', 'label' => 'Neighbor weighting', 'options' => ['uniform', 'distance'], 'default' => 'uniform'],
            ],
        ],
        'naive_bayes' => [
            'problem_type' => 'classification',
            'label' => 'Naive Bayes',
            'description' => 'A fast probabilistic baseline based on conditional independence assumptions.',
            'strengths' => ['Very fast', 'Works well as a baseline', 'Useful with limited training data'],
            'weaknesses' => ['Independence assumption is often unrealistic', 'Probability estimates may be poorly calibrated'],
            'when_not_to_use' => ['Features are strongly dependent and interactions dominate'],
            'expected_training_time' => 'Usually under a second for classroom datasets.',
            'supports_probability' => true,
            'supports_feature_importance' => false,
            'defaults' => ['var_smoothing' => 1.0e-9],
            'parameters' => [
                'var_smoothing' => ['type' => 'float', 'label' => 'Variance smoothing', 'min' => 1.0e-12, 'max' => 0.01, 'step' => 1.0e-9, 'default' => 1.0e-9],
            ],
        ],
        'svm' => [
            'problem_type' => 'classification',
            'label' => 'Support Vector Machine',
            'description' => 'Finds a separating boundary and can model nonlinear relationships with kernels.',
            'strengths' => ['Strong on medium-sized datasets', 'Effective in high-dimensional spaces', 'Flexible kernels'],
            'weaknesses' => ['Slower on large datasets', 'Needs scaling', 'Harder to explain'],
            'when_not_to_use' => ['Very large row counts', 'When transparent decision rules are required'],
            'expected_training_time' => 'A few seconds to several minutes depending on row count.',
            'supports_probability' => true,
            'supports_feature_importance' => false,
            'defaults' => ['c' => 1.0, 'kernel' => 'rbf', 'gamma' => 'scale'],
            'parameters' => [
                'c' => ['type' => 'float', 'label' => 'Regularization strength (C)', 'min' => 0.01, 'max' => 100.0, 'step' => 0.01, 'default' => 1.0],
                'kernel' => ['type' => 'select', 'label' => 'Kernel', 'options' => ['rbf', 'linear', 'poly'], 'default' => 'rbf'],
                'gamma' => ['type' => 'select', 'label' => 'Gamma', 'options' => ['scale', 'auto'], 'default' => 'scale'],
            ],
        ],
        'gradient_boosting' => [
            'problem_type' => 'classification',
            'label' => 'Gradient Boosting Classifier',
            'description' => 'Builds trees sequentially so each new tree corrects errors made by the previous ensemble.',
            'strengths' => ['Strong nonlinear performance', 'Supports probability estimates', 'Learning rate controls how quickly the ensemble adapts'],
            'weaknesses' => ['More sensitive to hyperparameters', 'Sequential training can be slower than Random Forest'],
            'when_not_to_use' => ['Very noisy small datasets without cross-validation', 'When a simple transparent model is required'],
            'expected_training_time' => 'Usually several seconds to a few minutes depending on rows and estimators.',
            'supports_probability' => true,
            'supports_feature_importance' => true,
            'defaults' => ['n_estimators' => 100, 'learning_rate' => 0.1, 'max_depth' => 3],
            'parameters' => [
                'n_estimators' => ['type' => 'integer', 'label' => 'Number of boosting stages', 'min' => 25, 'max' => 500, 'step' => 25, 'default' => 100],
                'learning_rate' => ['type' => 'float', 'label' => 'Learning rate', 'min' => 0.01, 'max' => 1.0, 'step' => 0.01, 'default' => 0.1],
                'max_depth' => ['type' => 'integer', 'label' => 'Tree maximum depth', 'min' => 1, 'max' => 10, 'step' => 1, 'default' => 3],
            ],
        ],
        'kmeans' => [
            'problem_type' => 'clustering',
            'label' => 'K-Means Clustering',
            'description' => 'Groups records into similarity-based clusters without a target column.',
            'strengths' => ['Simple unsupervised baseline', 'Fast on numeric classroom datasets', 'Useful for exploratory segmentation'],
            'weaknesses' => ['Requires numeric scaled features', 'Cluster count must be chosen', 'Sensitive to outliers'],
            'when_not_to_use' => ['Irregular non-spherical clusters', 'Datasets dominated by categorical variables'],
            'expected_training_time' => 'Usually a few seconds for classroom-sized datasets.',
            'supports_probability' => false,
            'supports_feature_importance' => false,
            'defaults' => ['n_clusters' => 3, 'n_init' => 10],
            'parameters' => [
                'n_clusters' => ['type' => 'integer', 'label' => 'Number of clusters', 'min' => 2, 'max' => 12, 'step' => 1, 'default' => 3],
                'n_init' => ['type' => 'integer', 'label' => 'Initialization runs', 'min' => 5, 'max' => 30, 'step' => 5, 'default' => 10],
            ],
        ],
        'linear_regression' => [
            'problem_type' => 'regression',
            'label' => 'Linear Regression',
            'description' => 'Models a continuous target as a weighted linear combination of features.',
            'strengths' => ['Fast', 'Interpretable coefficients', 'Good baseline'],
            'weaknesses' => ['Misses nonlinear relationships', 'Sensitive to outliers and multicollinearity'],
            'when_not_to_use' => ['The relationship is strongly nonlinear', 'Residual variance changes severely across predictions'],
            'expected_training_time' => 'Usually under a few seconds.',
            'supports_probability' => false,
            'supports_feature_importance' => true,
            'defaults' => ['fit_intercept' => true],
            'parameters' => [],
        ],
        'random_forest_regressor' => [
            'problem_type' => 'regression',
            'label' => 'Random Forest Regressor',
            'description' => 'A nonlinear ensemble regressor that averages many trees.',
            'strengths' => ['Captures nonlinear relationships', 'Handles interactions', 'Provides feature importance'],
            'weaknesses' => ['Larger artifacts', 'Cannot extrapolate beyond learned target ranges well'],
            'when_not_to_use' => ['When a simple equation is required', 'When extrapolation is the main goal'],
            'expected_training_time' => 'A few seconds to under a minute.',
            'supports_probability' => false,
            'supports_feature_importance' => true,
            'defaults' => ['n_estimators' => 150, 'max_depth' => 12, 'min_samples_split' => 2],
            'parameters' => [
                'n_estimators' => ['type' => 'integer', 'label' => 'Number of trees', 'min' => 25, 'max' => 500, 'step' => 25, 'default' => 150],
                'max_depth' => ['type' => 'integer', 'label' => 'Maximum depth', 'min' => 2, 'max' => 40, 'step' => 1, 'default' => 12],
                'min_samples_split' => ['type' => 'integer', 'label' => 'Minimum samples to split', 'min' => 2, 'max' => 50, 'step' => 1, 'default' => 2],
            ],
        ],
        'gradient_boosting_regressor' => [
            'problem_type' => 'regression',
            'label' => 'Gradient Boosting Regressor',
            'description' => 'Fits a sequence of shallow trees that progressively reduce regression error.',
            'strengths' => ['Captures nonlinear relationships', 'Learning rate supports controlled tuning', 'Often strong on structured tabular data'],
            'weaknesses' => ['Can overfit when trees are too deep', 'Training is sequential and parameter-sensitive'],
            'when_not_to_use' => ['Very small noisy datasets without cross-validation', 'When extrapolation beyond the observed target range is essential'],
            'expected_training_time' => 'Usually several seconds to a few minutes depending on rows and estimators.',
            'supports_probability' => false,
            'supports_feature_importance' => true,
            'defaults' => ['n_estimators' => 100, 'learning_rate' => 0.1, 'max_depth' => 3],
            'parameters' => [
                'n_estimators' => ['type' => 'integer', 'label' => 'Number of boosting stages', 'min' => 25, 'max' => 500, 'step' => 25, 'default' => 100],
                'learning_rate' => ['type' => 'float', 'label' => 'Learning rate', 'min' => 0.01, 'max' => 1.0, 'step' => 0.01, 'default' => 0.1],
                'max_depth' => ['type' => 'integer', 'label' => 'Tree maximum depth', 'min' => 1, 'max' => 10, 'step' => 1, 'default' => 3],
            ],
        ],
        'decision_tree_regressor' => [
            'problem_type' => 'regression',
            'label' => 'Decision Tree Regressor',
            'description' => 'Predicts numeric outcomes through hierarchical decision rules.',
            'strengths' => ['Nonlinear', 'Readable structure', 'Fast'],
            'weaknesses' => ['Can overfit', 'Predictions are piecewise constant'],
            'when_not_to_use' => ['Small noisy datasets without pruning'],
            'expected_training_time' => 'Usually under a few seconds.',
            'supports_probability' => false,
            'supports_feature_importance' => true,
            'defaults' => ['max_depth' => 8, 'min_samples_split' => 2],
            'parameters' => [
                'max_depth' => ['type' => 'integer', 'label' => 'Maximum depth', 'min' => 2, 'max' => 30, 'step' => 1, 'default' => 8],
                'min_samples_split' => ['type' => 'integer', 'label' => 'Minimum samples to split', 'min' => 2, 'max' => 50, 'step' => 1, 'default' => 2],
            ],
        ],
    ],
];
